### ISSUE TITLE
Issue with underscored engine names

### ISSUE THREAD

**Issue by ChrisLusted** [T-Dnzt/Modular-Engine#1]
Thanks for the gem, has worked great following the modular rails book.

I've now come up against a problem generating engines with more than one word names. 

Such as:

```
bundle exec rails g modular:engine engines/blah_images --namespace=Blah
```

It will output folder structure and module name like:

```
app/controllers/blah/blahimages/application_controller.rb 


module Blah
  module Blahimages
```

instead of what I would expect:

```
app/controllers/blah/blah_images/application_controller.rb 


module Blah
  module BlahImages
```

Am I doing something wrong here?

Thanks in advance

**Comment by ChrisLusted** [comment]
I've tracked it down to this pull request https://github.com/T-Dnzt/Modular-Engine/pull/2. 

Seems to work fine for my use case but let me know if any issues

**Comment by T-Dnzt** [comment]
@ChrisLusted I will give it a try tomorrow and if everything works fine, I will get it merged. ;)
